package com.sergio.refacto.tools;

public class Constants {

    public static final Short[] TOOL_LIST = {7, 8, 9, 10, 11, 12, 13, 14, 51, 52, 54, 55, 57, 58, 145, 146, 148, 149, 154, 155, 157, 158, 169, 170, 172, 173};

    public static final String[] BLOCK_NAMES = {"air", "dirt", "stone",
            "copper_ore", "iron_ore", "silver_ore", "gold_ore",
            "wood", "workbench",
            "wooden_chest", "stone_chest",
            "copper_chest", "iron_chest", "silver_chest", "gold_chest",
            "tree", "leaves", "furnace", "coal",
            "lumenstone",
            "wooden_torch", "coal_torch", "lumenstone_torch",
            "furnace_on",
            "wooden_torch_left", "wooden_torch_right",
            "coal_torch_left", "coal_torch_right",
            "lumenstone_torch_left", "lumenstone_torch_right",
            "tree_root",
            "zinc_ore", "rhymestone_ore", "obdurite_ore",
            "aluminum_ore", "lead_ore", "uranium_ore",
            "zythium_ore", "zythium_ore_on", "silicon_ore",
            "irradium_ore", "nullstone", "meltstone", "skystone",
            "magnetite_ore",
            "sand", "snow", "glass",
            "sunflower_stage_1", "sunflower_stage_2", "sunflower_stage_3",
            "moonflower_stage_1", "moonflower_stage_2", "moonflower_stage_3",
            "dryweed_stage_1", "dryweed_stage_2", "dryweed_stage_3",
            "greenleaf_stage_1", "greenleaf_stage_2", "greenleaf_stage_3",
            "frostleaf_stage_1", "frostleaf_stage_2", "frostleaf_stage_3",
            "caveroot_stage_1", "caveroot_stage_2", "caveroot_stage_3",
            "skyblossom_stage_1", "skyblossom_stage_2", "skyblossom_stage_3",
            "void_rot_stage_1", "void_rot_stage_2", "void_rot_stage_3",
            "grass", "jungle_grass", "swamp_grass",
            "mud", "sandstone",
            "marshleaf_stage_1", "marshleaf_stage_2", "marshleaf_stage_3",
            "zinc_chest", "rhymestone_chest", "obdurite_chest",
            "tree_no_bark", "cobblestone",
            "chiseled_stone", "chiseled_cobblestone", "stone_bricks",
            "clay", "clay_bricks", "varnished_wood",
            "dirt_trans", "magnetite_ore_trans", "grass_trans",
            "zythium_wire_0", "zythium_wire_1", "zythium_wire_2", "zythium_wire_3", "zythium_wire_4", "zythium_wire_5",
            "zythium_torch", "zythium_torch_left", "zythium_torch_right", "zythium_lamp", "zythium_lamp_on",
            "lever", "lever_on", "lever_left", "lever_left_on", "lever_right", "lever_right_on",
            "zythium_amplifier_right", "zythium_amplifier_down", "zythium_amplifier_left", "zythium_amplifier_up",
            "zythium_amplifier_right_on", "zythium_amplifier_down_on", "zythium_amplifier_left_on", "zythium_amplifier_up_on",
            "zythium_inverter_right", "zythium_inverter_down", "zythium_inverter_left", "zythium_inverter_up",
            "zythium_inverter_right_on", "zythium_inverter_down_on", "zythium_inverter_left_on", "zythium_inverter_up_on",
            "button_left", "button_left_on", "button_right", "button_right_on", "wooden_pressure_plate", "wooden_pressure_plate_on",
            "stone_pressure_plate", "stone_pressure_plate_on", "zythium_pressure_plate", "zythium_pressure_plate_on",
            "zythium_delayer_1_right", "zythium_delayer_1_down", "zythium_delayer_1_left", "zythium_delayer_1_up",
            "zythium_delayer_1_right_on", "zythium_delayer_1_down_on", "zythium_delayer_1_left_on", "zythium_delayer_1_up_on",
            "zythium_delayer_2_right", "zythium_delayer_2_down", "zythium_delayer_2_left", "zythium_delayer_2_up",
            "zythium_delayer_2_right_on", "zythium_delayer_2_down_on", "zythium_delayer_2_left_on", "zythium_delayer_2_up_on",
            "zythium_delayer_4_right", "zythium_delayer_4_down", "zythium_delayer_4_left", "zythium_delayer_4_up",
            "zythium_delayer_4_right_on", "zythium_delayer_4_down_on", "zythium_delayer_4_left_on", "zythium_delayer_4_up_on",
            "zythium_delayer_8_right", "zythium_delayer_8_down", "zythium_delayer_8_left", "zythium_delayer_8_up",
            "zythium_delayer_8_right_on", "zythium_delayer_8_down_on", "zythium_delayer_8_left_on", "zythium_delayer_8_up_on"};

    public static final String[] DIRS = {"center", "tdown_both", "tdown_cw", "tdown_ccw",
            "tdown", "tup_both", "tup_cw", "tup_ccw",
            "tup", "leftright", "tright_both", "tright_cw",
            "tright_ccw", "tright", "upleftdiag", "upleft",
            "downleftdiag", "downleft", "left", "tleft_both",
            "tleft_cw", "tleft_ccw", "tleft", "uprightdiag",
            "upright", "downrightdiag", "downright", "right",
            "updown", "up", "down", "single"};

    public static final String[] UI_ITEMS = {"Air", "Dirt", "Stone",
            "Copper Ore", "Iron Ore", "Silver Ore", "Gold Ore",
            "Copper Pick", "Iron Pick", "Silver Pick", "Gold Pick",
            "Copper Axe", "Iron Axe", "Silver Axe", "Gold Axe",
            "Wood", "Copper Sword", "Iron Sword", "Silver Sword", "Gold Sword",
            "Workbench",
            "Wooden Chest", "Stone Chest",
            "Copper Chest", "Iron Chest", "Silver Chest", "Gold Chest",
            "Furnace", "Coal",
            "Copper Ingot", "Iron Ingot", "Silver Ingot", "Gold Ingot",
            "Stone Lighter", "Lumenstone",
            "Wooden Torch", "Coal Torch", "Lumenstone Torch",
            "Zinc Ore", "Rhymestone Ore", "Obdurite Ore",
            "Aluminum Ore", "Lead Ore", "Uranium Ore",
            "Zythium Ore", "Silicon Ore",
            "Irradium Ore", "Nullstone", "Meltstone", "Skystone",
            "Magnetite Ore",
            "Zinc Pick", "Zinc Axe", "Zinc Sword",
            "Rhymestone Pick", "Rhymestone Axe", "Rhymestone Sword",
            "Obdurite Pick", "Obdurite Axe", "Obdurite Sword",
            "Zinc Ingot", "Rhymestone Ingot", "Obdurite Ingot",
            "Aluminum Ingot", "Lead Ingot", "Uranium Bar", "Refined Uranium",
            "Zythium Bar", "Silicon Bar",
            "Irradium Ingot", "Nullstone Bar", "Meltstone Bar", "Skystone Bar",
            "Magnetite Ingot",
            "Sand", "Snow", "Glass",
            "Sunflower Seeds", "Sunflower", "Moonflower Seeds", "Moonflower",
            "Dryweed Seeds", "Dryweed", "Greenleaf Seeds", "Greenleaf",
            "Frostleaf Seeds", "Frostleaf", "Caveroot Seeds", "Caveroot",
            "Skyblossom Seeds", "Skyblossom", "Void Rot Seeds", "Void Rot",
            "Mud", "Sandstone",
            "Marshleaf Seeds", "Marshleaf",
            "Blue Goo", "Green Goo", "Red Goo", "Yellow Goo", "Black Goo", "White Goo",
            "Astral Shard", "Rotten Chunk",
            "Copper Helmet", "Copper Chestplate", "Copper Leggings", "Copper Greaves",
            "Iron Helmet", "Iron Chestplate", "Iron Leggings", "Iron Greaves",
            "Silver Helmet", "Silver Chestplate", "Silver Leggings", "Silver Greaves",
            "Gold Helmet", "Gold Chestplate", "Gold Leggings", "Gold Greaves",
            "Zinc Helmet", "Zinc Chestplate", "Zinc Leggings", "Zinc Greaves",
            "Rhymestone Helmet", "Rhymestone Chestplate", "Rhymestone Leggings", "Rhymestone Greaves",
            "Obdurite Helmet", "Obdurite Chestplate", "Obdurite Leggings", "Obdurite Greaves",
            "Aluminum Helmet", "Aluminum Chestplate", "Aluminum Leggings", "Aluminum Greaves",
            "Lead Helmet", "Lead Chestplate", "Lead Leggings", "Lead Greaves",
            "Zythium Helmet", "Zythium Chestplate", "Zythium Leggings", "Zythium Greaves",
            "Aluminum Pick", "Aluminum Axe", "Aluminum Sword",
            "Lead Pick", "Lead Axe", "Lead Sword",
            "Zinc Chest", "Rhymestone Chest", "Obdurite Chest",
            "Wooden Pick", "Wooden Axe", "Wooden Sword",
            "Stone Pick", "Stone Axe", "Stone Sword",
            "Bark", "Cobblestone",
            "Chiseled Stone", "Chiseled Cobblestone", "Stone Bricks",
            "Clay", "Clay Bricks", "Varnish", "Varnished Wood",
            "Magnetite Pick", "Magnetite Axe", "Magnetite Sword",
            "Irradium Pick", "Irradium Axe", "Irradium Sword",
            "Zythium Wire", "Zythium Torch", "Zythium Lamp", "Lever",
            "Charcoal", "Zythium Amplifier", "Zythium Inverter", "Button",
            "Wooden Pressure Plate", "Stone Pressure Plate", "Zythium Pressure Plate",
            "Zythium Delayer", "Zythium Delayer", "Zythium Delayer", "Zythium Delayer", "Wrench"};

    public static final  String[] ITEMS = {"air", "blocks/dirt", "blocks/stone", "ores/copper_ore",
            "ores/iron_ore", "ores/silver_ore", "ores/gold_ore", "tools/copper_pick",
            "tools/iron_pick", "tools/silver_pick", "tools/gold_pick", "tools/copper_axe",
            "tools/iron_axe", "tools/silver_axe", "tools/gold_axe", "blocks/wood",
            "tools/copper_sword", "tools/iron_sword", "tools/silver_sword", "tools/gold_sword",
            "machines/workbench",
            "machines/wooden_chest", "machines/stone_chest",
            "machines/copper_chest", "machines/iron_chest", "machines/silver_chest", "machines/gold_chest",
            "machines/furnace",
            "ores/coal", "ingots/copper_ingot", "ingots/iron_ingot", "ingots/silver_ingot", "ingots/gold_ingot",
            "tools/stone_lighter", "ores/lumenstone",
            "torches/wooden_torch", "torches/coal_torch", "torches/lumenstone_torch",
            "ores/zinc_ore", "ores/rhymestone_ore", "ores/obdurite_ore",
            "ores/aluminum_ore", "ores/lead_ore", "ores/uranium_ore",
            "ores/zythium_ore", "ores/silicon_ore",
            "ores/irradium_ore", "ores/nullstone", "ores/meltstone", "ores/skystone",
            "ores/magnetite_ore",
            "tools/zinc_pick", "tools/zinc_axe", "tools/zinc_sword",
            "tools/rhymestone_pick", "tools/rhymestone_axe", "tools/rhymestone_sword",
            "tools/obdurite_pick", "tools/obdurite_axe", "tools/obdurite_sword",
            "ingots/zinc_ingot", "ingots/rhymestone_ingot", "ingots/obdurite_ingot",
            "ingots/aluminum_ingot", "ingots/lead_ingot", "ingots/uranium_bar", "ingots/refined_uranium",
            "ingots/zythium_bar", "ingots/silicon_bar",
            "ingots/irradium_ingot", "ingots/nullstone_bar", "ingots/meltstone_bar", "ingots/skystone_bar",
            "ingots/magnetite_ingot",
            "blocks/sand", "blocks/snow", "blocks/glass",
            "seeds/sunflower_seeds", "herbs/sunflower", "seeds/moonflower_seeds", "herbs/moonflower",
            "seeds/dryweed_seeds", "herbs/dryweed", "seeds/greenleaf_seeds", "herbs/greenleaf",
            "seeds/frostleaf_seeds", "herbs/frostleaf", "seeds/caveroot_seeds", "herbs/caveroot",
            "seeds/skyblossom_seeds", "herbs/skyblossom", "seeds/void_rot_seeds", "herbs/void_rot",
            "blocks/mud", "blocks/sandstone",
            "seeds/marshleaf_seeds", "herbs/marshleaf",
            "goo/blue_goo", "goo/green_goo", "goo/red_goo", "goo/yellow_goo", "goo/black_goo", "goo/white_goo",
            "goo/astral_shard", "goo/rotten_chunk",
            "armor/copper_helmet", "armor/copper_chestplate", "armor/copper_leggings", "armor/copper_greaves",
            "armor/iron_helmet", "armor/iron_chestplate", "armor/iron_leggings", "armor/iron_greaves",
            "armor/silver_helmet", "armor/silver_chestplate", "armor/silver_leggings", "armor/silver_greaves",
            "armor/gold_helmet", "armor/gold_chestplate", "armor/gold_leggings", "armor/gold_greaves",
            "armor/zinc_helmet", "armor/zinc_chestplate", "armor/zinc_leggings", "armor/zinc_greaves",
            "armor/rhymestone_helmet", "armor/rhymestone_chestplate", "armor/rhymestone_leggings", "armor/rhymestone_greaves",
            "armor/obdurite_helmet", "armor/obdurite_chestplate", "armor/obdurite_leggings", "armor/obdurite_greaves",
            "armor/aluminum_helmet", "armor/aluminum_chestplate", "armor/aluminum_leggings", "armor/aluminum_greaves",
            "armor/lead_helmet", "armor/lead_chestplate", "armor/lead_leggings", "armor/lead_greaves",
            "armor/zythium_helmet", "armor/zythium_chestplate", "armor/zythium_leggings", "armor/zythium_greaves",
            "tools/aluminum_pick", "tools/aluminum_axe", "tools/aluminum_sword",
            "tools/lead_pick", "tools/lead_axe", "tools/lead_sword",
            "machines/zinc_chest", "machines/rhymestone_chest", "machines/obdurite_chest",
            "tools/wooden_pick", "tools/wooden_axe", "tools/wooden_sword",
            "tools/stone_pick", "tools/stone_axe", "tools/stone_sword",
            "goo/bark", "blocks/cobblestone",
            "blocks/chiseled_stone", "blocks/chiseled_cobblestone", "blocks/stone_bricks",
            "blocks/clay", "blocks/clay_bricks", "potions/varnish", "blocks/varnished_wood",
            "tools/magnetite_pick", "tools/magnetite_axe", "tools/magnetite_sword",
            "tools/irradium_pick", "tools/irradium_axe", "tools/irradium_sword",
            "wires/zythium_wire", "torches/zythium_torch", "blocks/zythium_lamp", "misc/lever",
            "dust/charcoal", "wires/zythium_amplifier", "wires/zythium_inverter", "misc/button",
            "misc/wooden_pressure_plate", "misc/stone_pressure_plate", "misc/zythium_pressure_plate",
            "wires/zythium_delayer_1", "wires/zythium_delayer_2", "wires/zythium_delayer_4", "wires/zythium_delayer_8", "tools/wrench"};

    public static final boolean[] BLOCK_CDS = {false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};
    public static final boolean[] SOLID = {false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, true, true, true, false, false, false, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};
    public static final boolean[] L_TRANS = {false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, false, false, false, false, false, false, false, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false};
    public static final boolean[] POWERS = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, true, false, true, false, true, false, false, false, false, true, true, true, true, true, true, true, true, false, false, false, false, false, true, false, true, false, true, false, true, false, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true, false, false, false, false, true, true, true, true};
    public static final double[] CONDUCTS = {-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0, 0, 0, -1, -1, -1, 0, -1, 0, -1, 0, -1, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, -1, -1, -1, 0, -1, 0, -1, 0, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    public static final boolean[] RECEIVES = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true};
    public static final boolean[] WIRE_C = {false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true};
    public static final int[] SKY_COLORS = {28800, 28980, 29160, 29340, 29520, 29700, 29880, 30060, 30240, 30420, 30600, 30780, 30960, 31140, 31320, 31500, 31680, 31860, 32040, 32220, 72000, 72180, 72360, 72540, 72720, 72900, 73080, 73260, 73440, 73620, 73800, 73980, 74160, 74340, 74520, 74700, 74880, 75060, 75240, 75420};
}
